# Generated by Django 2.2.3 on 2019-08-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
