# Generated by Django 2.2.3 on 2019-07-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
    ]
