# Generated by Django 2.2.3 on 2019-07-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ED', 'Evening dresses'), ('WD', 'Wedding dresses'), ('OD', 'Occasion dresses'), ('MXD', 'Maxi dresses'), ('MND', 'Mini dresses'), ('PD', 'Party dresses'), ('ED', 'Cocktail dresses'), ('WD', 'Day dresses'), ('OD', 'Festival dresses')], default='WD', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
