# Generated by Django 2.2.4 on 2019-08-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_auto_20190821_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['title']},
        ),
    ]
