# Generated by Django 2.2.3 on 2019-08-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_order_user_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
