# Generated by Django 2.2.3 on 2019-07-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_auto_20190716_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
