# Generated by Django 2.2.4 on 2019-09-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_auto_20190824_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
