# Generated by Django 2.2.3 on 2019-07-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DR', 'Dresses'), ('SH', 'Shoes'), ('SU', 'Suits'), ('VL', 'Veils'), ('RN', 'Rings'), ('FL', 'Flowers'), ('HA', 'Hair Accessories'), ('BP', 'Purses'), ('NT', 'Neckties'), ('SH', 'Shirts'), ('BS', 'Belts')], max_length=2),
        ),
    ]
