# Generated by Django 2.2.4 on 2019-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_refund_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
