# Generated by Django 2.2.3 on 2019-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Test Description'),
            preserve_default=False,
        ),
    ]
