# Generated by Django 2.2.3 on 2019-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_auto_20190716_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DRESSES', 'Dresses'), ('SHOES', 'Shoes'), ('SUITS', 'Suits'), ('VEILS', 'Veils'), ('RINGS', 'Rings'), ('FLOWERS', 'Flowers'), ('HAIR ACCESSORIES', 'Hair Accessories'), ('PURSES', 'Purses'), ('NECKTIES', 'Neckties'), ('SHIRTS', 'Shirts'), ('BELTS', 'Belts')], max_length=20),
        ),
    ]
