# Generated by Django 2.2.3 on 2019-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_order_user_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
