# Generated by Django 2.2.3 on 2019-07-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_auto_20190714_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
