# Generated by Django 2.2.3 on 2019-07-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0009_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
