# Generated by Django 2.2.3 on 2019-07-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0011_auto_20190719_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
