# Generated by Django 2.2.3 on 2019-07-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0012_remove_coupon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='numbers_of_usages_allowed',
            new_name='number_of_usages_allowed',
        ),
    ]
