# Generated by Django 2.2.3 on 2019-07-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0014_customerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
